server.port=8080
spring.application.name=smartlogix-bff

# URLs de los microservicios
inventario.ms.url=http://localhost:8081
pedidos.ms.url=http://localhost:8082

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Actuator / Prometheus
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.health.circuitbreakers.enabled=true

# Circuit Breaker - Inventario
resilience4j.circuitbreaker.instances.inventario.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventario.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventario.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.inventario.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventario.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventario.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.inventario.automaticTransitionFromOpenToHalfOpenEnabled=true

# Circuit Breaker - Pedidos
resilience4j.circuitbreaker.instances.pedidos.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.pedidos.slidingWindowSize=5
resilience4j.circuitbreaker.instances.pedidos.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.pedidos.failureRateThreshold=50
resilience4j.circuitbreaker.instances.pedidos.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.pedidos.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.pedidos.automaticTransitionFromOpenToHalfOpenEnabled=true