server.port=8080
spring.application.name=smartlogix-bff

# URLs de los microservicios
inventario.ms.url=http://localhost:8081
pedidos.ms.url=http://localhost:8082

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html